In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [ ]:
# # load the dataset
# # data = pd.read_csv('Churn_Modelling.csv')
# # data.head()



# # Load dataset
# data = pd.read_csv('Churn_Modelling.csv')

# # Check it loaded
# print(data.shape)
# data.head()

(10000, 14)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
#

In [ ]:
# #preprocessing data 
# # removing irrelevant columns
# data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)
# #axix=1  column wise
# data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
# print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
# # encoding categorical variables
# # label_encoder_gender = LabelEncoder()
# # data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
# # datafrom sklearn.preprocessing import LabelEncoder

# label_encoder_gender = LabelEncoder()
# x_train['Gender'] = label_encoder_gender.fit_transform(x_train['Gender'])
# x_test['Gender'] = label_encoder_gender.transform(x_test['Gender'])

In [ ]:
# #onehot encode geography
# from sklearn.preprocessing import OneHotEncoder
# onehot_encoder_geo = OneHotEncoder()
# geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
# geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [ ]:
# geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
# onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [ ]:
# geo_encoder_df = pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

# geo_encoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [ ]:
# #combine one hot encoder columns with the original data
# data = pd.concat([data.drop('Geography',axis=1),geo_encoder_df],axis=1)
# data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,Female,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,Female,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,Female,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,Female,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,Female,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [ ]:
# geo_encoded_test = onehot_encoder_geo.transform(x_test[['Geography']]).toarray()

# geo_encoded_test_df = pd.DataFrame(
#     geo_encoded_test,
#     columns=onehot_encoder_geo.get_feature_names_out(['Geography'])
# )

# x_test = x_test.drop('Geography', axis=1)

# x_test = pd.concat([x_test.reset_index(drop=True), geo_encoded_test_df], axis=1)

KeyError: "None of [Index(['Geography'], dtype='object')] are in the [columns]"

In [ ]:
# #save the encoders and scaler
# with open('label_encoder_gender.pkl','wb') as file:
#     pickle.dump(label_encoder_gender,file)

# with open('onehot_encoder_geo.pkl','wb') as file:
#     pickle.dump(onehot_encoder_geo,file)

In [ ]:
# # Load dataset
# data = pd.read_csv('Churn_Modelling.csv')

# # ✅ CLEAN DATA
# data = data[data['Gender'].isin(['Male', 'Female'])]

# # Remove any missing values
# data = data.dropna()

In [ ]:
# print(x_train.dtypes)

RowNumber              int64
CustomerId             int64
Surname               object
CreditScore            int64
Gender                 int32
Age                    int64
Tenure                 int64
Balance              float64
NumOfProducts          int64
HasCrCard              int64
IsActiveMember         int64
EstimatedSalary      float64
Geography_France     float64
Geography_Germany    float64
Geography_Spain      float64
dtype: object

In [ ]:
# print(x_train.select_dtypes(include=['object']).columns)

Index(['Surname'], dtype='object')

In [ ]:
# from sklearn.preprocessing import OneHotEncoder

# onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')

# geo_encoded = onehot_encoder_geo.fit_transform(x_train[['Geography']]).toarray()

# geo_encoded_df = pd.DataFrame(
#     geo_encoded,
#     columns=onehot_encoder_geo.get_feature_names_out(['Geography'])
# )

# x_train = x_train.drop('Geography', axis=1)
# x_train = pd.concat([x_train.reset_index(drop=True), geo_encoded_df], axis=1)

KeyError: "None of [Index(['Geography'], dtype='object')] are in the [columns]"

In [ ]:
# x_train = x_train.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
# x_test = x_test.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [ ]:
# print(x_train.dtypes)

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
dtype: object

In [ ]:
# from sklearn.preprocessing import LabelEncoder

# label_encoder_gender = LabelEncoder()

# x_train['Gender'] = label_encoder_gender.fit_transform(x_train['Gender'])
# x_test['Gender'] = label_encoder_gender.transform(x_test['Gender'])

In [ ]:
# if 'Geography' in x_train.columns:
#     x_train = x_train.drop('Geography', axis=1)
#     x_test = x_test.drop('Geography', axis=1)

In [ ]:
# print(x_train.dtypes)

CreditScore          int64
Gender               int32
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
dtype: object

In [ ]:
# # divide the dataset into independent and dependent features
# x = data.drop('Exited',axis=1)
# y = data['Exited']

# #split the dataset in traning and testing sets
# x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)


# #scale these features
# scaler = StandardScaler()
# x_train = scaler.fit_transform(x_train)
# x_test=scaler.transform(x_test)

ValueError: could not convert string to float: "P'an"

In [ ]:
# x_train

array([[ 0.19350318, -1.10030863, -0.08281017, ..., -0.57672488,
        -0.57576275, -0.01118034],
       [-0.24071685,  0.90849214,  1.25543947, ...,  1.733929  ,
        -0.57576275, -0.01118034],
       [-0.6645983 ,  0.90849214,  1.82897503, ..., -0.57672488,
        -0.57576275, -0.01118034],
       ...,
       [ 0.87584893, -1.10030863, -0.08281017, ..., -0.57672488,
        -0.57576275, -0.01118034],
       [ 0.17282603,  0.90849214,  0.39513613, ..., -0.57672488,
        -0.57576275, -0.01118034],
       [ 1.16532895, -1.10030863, -0.65634573, ..., -0.57672488,
         1.73682649, -0.01118034]], shape=(16002, 14))

In [ ]:
# with open('scaler.pkl','wb') as file:
#     pickle.dump(scaler,file)

In [ ]:
# #ann implementation
# import tensorflow as tf
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense
# from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
# import datetime

In [ ]:
# #build our ann mmodel
# model =Sequential([
#     Dense(64,activation='relu',input_shape=(x_train.shape[1],)), #HL1 connected with i/p layer
    
#     Dense(32,activation='relu'), #HL2
#     Dense(1,activation='sigmoid') #output layer
# ])

c:\Users\sivap\.conda\envs\ann_env\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
# model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,073 (12.00 KB)

 Trainable params: 3,073 (12.00 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# import tensorflow
# opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
# loss = tensorflow.keras.losses.BinaryCrossentropy()
# loss

In [ ]:
# #complie the model
# model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [ ]:
# # set up the tensorboard

# import datetime
# from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
# import os

# log_dir = "logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")



# tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [ ]:
#

In [ ]:
# #setup early stopping
# early_stopping_callback = EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [ ]:
# print(x.dtypes)
# print(y.dtype)

CreditScore            float64
Gender                   int64
Age                    float64
Tenure                 float64
Balance                float64
NumOfProducts          float64
HasCrCard              float64
IsActiveMember         float64
EstimatedSalary        float64
Geography_France       float64
Geography_Geography    float64
Geography_Germany      float64
Geography_Spain        float64
Geography_nan          float64
dtype: object
float64

In [ ]:
# #train the model
# history=model.fit(
    
#     x_train,y_train,validation_data=(x_test,y_test),epochs=100,
#     callbacks=[tensorflow_callback, early_stopping_callback]
# )

Epoch 1/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8047 - loss: nan - val_accuracy: 0.7971 - val_loss: nan
Epoch 2/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7960 - loss: nan - val_accuracy: 0.7971 - val_loss: nan
Epoch 3/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7960 - loss: nan - val_accuracy: 0.7971 - val_loss: nan
Epoch 4/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7960 - loss: nan - val_accuracy: 0.7971 - val_loss: nan
Epoch 5/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7960 - loss: nan - val_accuracy: 0.7971 - val_loss: nan
Epoch 6/100
501/501 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7960 - loss: nan - val_accuracy: 0.7971 - val_loss: nan

In [ ]:
# model.save('model.h5')

NameError: name 'model' is not defined

In [ ]:
# #load tensorboard extension
# %load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [ ]:
# %tensorboard --logdir logs

Reusing TensorBoard on port 6007 (pid 23164), started 0:00:11 ago. (Use '!kill 23164' to kill it.)

In [ ]:
import datetime
from tensorflow.keras.callbacks import TensorBoard

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorflow_callback = TensorBoard(log_dir=log_dir)

In [ ]:
history = model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=100,
    callbacks=[tensorflow_callback, early_stopping_callback]
)

In [ ]:
import os
print(os.listdir("logs/fit"))

In [ ]:
import datetime
import os
from tensorflow.keras.callbacks import TensorBoard

log_dir = os.path.join("C:/temp/tensorflow_logs",
                       datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))

os.makedirs(log_dir, exist_ok=True)

tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [ ]:
history = model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=3,
    callbacks=[tensorflow_callback]
)

In [ ]:
%load_ext tensorboard
%tensorboard --logdir logs/fit/20260319-194532